databases:
  - name: elekgo_app
    databaseName: railway
    user: postgres

services:
  - type: web
    name: elekgo_app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn elekgo.wsgi:application"
    envVars:
      - key: postgresql://${{ postgres }}:${{ stoWSHjBsQrSBZhHbpCm }}@${{ containers-us-west-162.railway.app }}:${{ 6517 }}/${{ railway }}
        fromDatabase:
          name: elekgo_app
          property: connectionString
      - key: django-insecure-6@n_9-qro102&&#6-qg23lb1nl=)fn3&2-^+2u^+ry^8^^7r*%
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4