# Generated by Django 4.1.2 on 2022-11-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bolt_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
