# Generated by Django 3.2.16 on 2022-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0002_alter_user_bolt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_aadhar_identification_num',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
